CREATE TABLE Library_User (
                              id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              full_name varchar(100) NOT NULL UNIQUE,
                              year_of_birth int NOT NULL,
                              role varchar
);

CREATE TABLE Book (
                      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      title varchar(100) NOT NULL,
                      author varchar(100) NOT NULL,
                      year int NOT NULL,
                      taken_at date,
                      user_id bigint REFERENCES Library_User(id) ON DELETE SET NULL
);